project_id = "mfmkxpdufcbwydixbbbe"

[functions.process-automatic-campaigns]
verify_jwt = false

[functions.send-response-notification]
verify_jwt = false

[functions.test-email-config]
verify_jwt = false

[functions.check-nps-pending]
verify_jwt = false

[functions.submit-embedded-response]
verify_jwt = false